"""Markdown reporter — human-readable duplication analysis."""

from __future__ import annotations

from datetime import datetime, timezone

from redup.core.models import DuplicationMap


def to_markdown(dup_map: DuplicationMap) -> str:
    """Serialize a DuplicationMap to Markdown format."""
    lines = []
    
    # Header
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append(f"# Code Duplication Analysis Report")
    lines.append(f"**Generated:** {now}")
    lines.append(f"**Project:** `{dup_map.project_path}`")
    lines.append("")
    
    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Files scanned | {dup_map.stats.files_scanned} |")
    lines.append(f"| Total lines | {dup_map.stats.total_lines:,} |")
    lines.append(f"| Duplicate groups | {dup_map.total_groups} |")
    lines.append(f"| Duplicate fragments | {dup_map.total_fragments} |")
    lines.append(f"| Recoverable lines | {dup_map.total_saved_lines:,} |")
    lines.append(f"| Scan time | {dup_map.stats.scan_time_ms:.0f}ms |")
    lines.append("")
    
    if dup_map.total_groups == 0:
        lines.append("✅ **No duplicate code found!**")
        lines.append("")
        return "\n".join(lines)
    
    # Duplicate groups
    lines.append("## Duplicate Groups")
    lines.append("")
    
    ranked = dup_map.sorted_by_impact()
    for i, group in enumerate(ranked, 1):
        impact_emoji = "🔴" if group.impact_score > 100 else "🟡" if group.impact_score > 30 else "🟢"
        
        lines.append(f"### {i}. {group.normalized_name or 'Unnamed'} {impact_emoji}")
        lines.append("")
        lines.append(f"- **Type:** `{group.duplicate_type.value.upper()}`")
        lines.append(f"- **Similarity:** {group.similarity_score:.2f}")
        lines.append(f"- **Occurrences:** {group.occurrences}")
        lines.append(f"- **Total lines:** {group.total_lines}")
        lines.append(f"- **Recoverable lines:** {group.saved_lines_potential}")
        lines.append(f"- **Impact score:** {group.impact_score:.1f}")
        lines.append("")
        
        lines.append("**Locations:**")
        lines.append("")
        for frag in group.fragments:
            fn_info = f" (`{frag.function_name}`)" if frag.function_name else ""
            class_info = f" class `{frag.class_name}`" if frag.class_name else ""
            lines.append(f"- `{frag.file}:{frag.line_start}-{frag.line_end}`{fn_info}{class_info}")
        lines.append("")
    
    # Refactoring suggestions
    if dup_map.suggestions:
        lines.append("## Refactoring Suggestions")
        lines.append("")
        
        for suggestion in dup_map.suggestions:
            risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(suggestion.risk_level.value, "⚪")
            
            lines.append(f"### Priority {suggestion.priority}: {suggestion.action.value} {risk_emoji}")
            lines.append("")
            lines.append(f"**Target module:** `{suggestion.new_module}`")
            lines.append("")
            lines.append(f"**Rationale:** {suggestion.rationale}")
            lines.append("")
            
            lines.append("**Affected files:**")
            for file_path in suggestion.original_files:
                lines.append(f"- `{file_path}`")
            lines.append("")
    
    # Footer
    lines.append("---")
    version = getattr(dup_map.stats, 'version', 'unknown')
    lines.append(f"*Report generated by [reDUP](https://github.com/semcod/redup) v{version}*")
    
    return "\n".join(lines)
