flowchart TD
    benchmark["benchmark<br/>2 funcs"]
    benchmarks__bench_libraries["benchmarks.bench_libraries<br/>4 funcs"]
    examples__01_basic_usage["examples.01_basic_usage<br/>1 funcs"]
    src__redup["src.redup<br/>372 funcs"]
    benchmark ==>|4| src__redup
    examples__01_basic_usage -->|3| src__redup
    benchmarks__bench_libraries -->|1| src__redup
